global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
# - "first.rules"
# - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'quarkus-metrics'
    metrics_path: 'q/metrics/prometheus'
    static_configs:
      - targets: [ 'quarkus_app_1:8080', 'quarkus_app_2:8080', 'quarkus_app_3:8080' ]
  - job_name: 'orchestration-library'
    static_configs:
    - targets: ['host.docker.internal:30015']
      # - targets: ['localhost:30015']
      # - targets: ['localhost:8000']
  # - job_name: 'stealer'
  #   metrics_path: 'stealer_metrics'
  #   static_configs:
  #     - targets: ['host.docker.internal:19091']  # Stealer metrics
  #     # - targets: ['localhost:19091']  # Stealer metrics
  # - job_name: 'donor'
  #   metrics_path: 'donor_metrics'
  #   static_configs:
  #     - targets: ['host.docker.internal:29092']  # Donor metrics
  #     # - targets: ['localhost:29092']

remote_write:
  - url: "http://prometheus-nats-adapter:5000/receive"
