prometheus:
  image: prom/prometheus:latest

nats:
  image: nats:latest

prometheusNatsAdapter:
  image: anejvovcakjob/aces:prometheus-nats-adapter
  natsUrl: nats://nats-server:4222
  natsStream: prometheus
  natsSubject: metrics

aggregationService:
  image: anejvovcakjob/aces:aggregation-service-jvm
  natsUrl: nats://nats-server:4222
  natsStream: prometheus
  natsInputSubjectPrefix: metrics
  natsOutputSubjectPrefix: aggregated_metrics

grafana:
  image: grafana/grafana:latest
  gFSecurityAdminPassword: admin
  service:
    port: 3000
    targetPort: 3000
    nodePort: 30000

ottelCollector:
  image: otel/opentelemetry-collector-contrib:latest
  configMapName: otel-collector-config
  configMapDataKey: otel-collector-config.yaml
  port: 8888
  volumeMountPath: /etc/otel-collector-config.yaml
  volumeMountSubPath: otel-collector-config.yaml

quarkusApp1:
  image: anejvovcakjob/aces:microservice-demo
  containerPort: 8080
  customersApiUrl: http://quarkus-app-2:8083/v1
  port: 8082
  targetPort: 8080

quarkusApp2:
  image: anejvovcakjob/aces:microservice-demo
  containerPort: 8080
  customersApiUrl: http://quarkus-app-3:8084/v1
  port: 8083
  targetPort: 8080

quarkusApp3:
  image: anejvovcakjob/aces:microservice-demo
  containerPort: 8080
  customersApiUrl: http://quarkus-app-1:8082/v1
  port: 8084
  targetPort: 8080
