prometheus:
  image: prom/prometheus:latest

nats:
  image: nats:latest

prometheusNatsAdapter:
  image: anejvovcakjob/aces:prometheus-nats-adapter
  natsUrl: nats://nats-server:4222
  natsStream: prometheus
  natsSubject: metrics

aggregationService:
  image: anejvovcakjob/aces:aggregation-service-jvm
  natsUrl: nats://nats-server:4222
  natsStream: prometheus
  natsInputSubjectPrefix: metrics
  natsOutputSubjectPrefix: aggregated_metrics

grafana:
  image: grafana/grafana:latest
  gFSecurityAdminPassword: admin

ottelCollector:
  image: otel/opentelemetry-collector-contrib:latest
  configMapName: otel-collector-config
  configMapDataKey: otel-collector-config.yaml
  port: 8888
  volumeMountPath: /etc/otel-collector-config.yaml
  volumeMountSubPath: otel-collector-config.yaml
