apiVersion: batch/v1
kind: Job
metadata:
  name: configure-jetstream-retention
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      containers:
      - name: nats-cli
        image: natsio/nats-box
        command: ["sh", "-c"]
        args:
          - |
            echo "Waiting for NATS server to be ready..."
            for i in $(seq 1 30); do
              nc -z nats-server 4222 && break
              sleep 2
            done

            echo "Updating retention for all JetStream streams..."
            nats stream ls --json | jq -r '.[].config.name' | while read stream; do
              echo "Updating stream: $stream"
              nats stream update "$stream" \
                --server nats://{{ .Values.nats.service.name }}:4222 \
                --retention limits \
                --max-msgs {{ .Values.nats.retention.maxMsgs }} \
                --max-bytes {{ .Values.nats.retention.maxBytes }} \
                --max-age {{ .Values.nats.retention.maxAge }} \
                --discard old
            done
      restartPolicy: OnFailure
