{{- if .Values.quarkusApp.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-app-2
  template:
    metadata:
      labels:
        app: quarkus-app-2
    spec:
      containers:
        - name: quarkus-app-2
          image: {{ .Values.quarkusApp.quarkusApp2.image }}
          ports:
            - containerPort: {{ .Values.quarkusApp.quarkusApp2.containerPort }}
          env:
            - name: CUSTOMERS_API_URL
              value: {{ .Values.quarkusApp.quarkusApp2.customersApiUrl }}
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-app-2
spec:
  selector:
    app: quarkus-app-2
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.quarkusApp.quarkusApp2.port }}
      targetPort: {{ .Values.quarkusApp.quarkusApp2.targetPort }}
{{- end }}