{
 "title": "ACES Orchestration API Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Total Requests (Pie Chart)",
   "type": "piechart",
   "gridPos": { "h": 16, "w": 9, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (base_endpoint) (label_replace(api_requests_total, \"base_endpoint\", \"$1\", \"endpoint\", \"^(/workload_action|/alerts|/tuning_parameters|/workload_request_decision)\"))",
     "legendFormat": "{{base_endpoint}}"
    }
   ]
  },
  {
   "title": "API Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "sum by (base_endpoint, status_code) (label_replace(api_requests_total, \"base_endpoint\", \"$1\", \"endpoint\", \"^(/workload_action|/alerts|/tuning_parameters|/workload_request_decision)\"))",
     "legendFormat": "{{base_endpoint}} [{{status_code}}]"
    }
   ]
  },
  {
   "title": "API Latency (P90)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by (le, base_endpoint, status_code) (label_replace(api_requests_latency_seconds_bucket, \"base_endpoint\", \"$1\", \"endpoint\", \"^(/workload_action|/alerts|/tuning_parameters|/workload_request_decision)\")))",
     "legendFormat": "{{base_endpoint}} [{{status_code}}]"
    }
   ]
  }
 ]
}