{
 "title": "Demo dashboard ACES",
 "time": { "from": "now-30m", "to": "now+10m" },
 "refresh": "auto",
 "panels": [
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running jobs (healthy)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum by(job) (up)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Available CPU cores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(system_cpu_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Overall CPU usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "avg(system_cpu_usage)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Request latency distribution [s]",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_max)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System CPU usage",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "avg(system_cpu_usage)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Process CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 18 },
   "targets": [
    { "expr": "sum(process_cpu_usage)", "legendFormat": "Actual" },
    {
     "expr": "sum(predict_linear(process_cpu_usage[3h], 60))",
     "legendFormat": "Predicted"
    }
   ]
  },
  {
   "title": "CPU usage per process",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 18 },
   "targets": [
    { "expr": "process_cpu_usage", "legendFormat": "__auto" }
   ]
  }
 ]
}