apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregation-service
  template:
    metadata:
      labels:
        app: aggregation-service
    spec:
      containers:
        - name: aggregation-service
          image: anejvovcakjob/aces:aggregation-service-jvm
          ports:
            - containerPort: 8080
          env:
            - name: NATS_URL
              value: "nats://nats-server:4222"
            - name: NATS_STREAM
              value: "prometheus"
            - name: NATS_INPUT_SUBJECT_PREFIX
              value: "metrics"
            - name: NATS_OUTPUT_SUBJECT_PREFIX
              value: "aggregated_metrics"


---

apiVersion: v1
kind: Service
metadata:
  name: aggregation-service
spec:
  selector:
    app: aggregation-demo
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8080
