apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  labels:
    name: grafana-datasource
data:
  prometheus-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service:80
        isDefault: true
        editable: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  labels:
    name: grafana-config
data:
  grafana.ini: |
    [security]
    allow_embedding = true
    
    [auth.proxy]
    enabled = true
    header_name = X-WEBAUTH-USER
    header_property = username
    auto_sign_up = true

    [users]
    auto_assign_org = true
    auto_assign_org_role = Viewer
