apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.grafana.service.name }}
  labels:
    app: {{ .Values.grafana.service.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.grafana.service.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.grafana.service.name }}
    spec:
      containers:
        - name: {{ .Values.grafana.service.name }}
          image: {{ .Values.grafana.image }}
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: {{ .Values.grafana.gFSecurityAdminUser }}
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: {{ .Values.grafana.gFSecurityAdminPassword }}
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-datasource
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-config
              mountPath: /etc/grafana
      volumes:
        - name: grafana-storage
          emptyDir: {}
        - name: grafana-datasource
          configMap:
            name: grafana-datasource
        - name: grafana-config
          configMap:
            name: grafana-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.grafana.service.name }}
  labels:
    app: {{ .Values.grafana.service.name  }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.grafana.service.port }}
      targetPort: {{ .Values.grafana.service.targetPort }}
      nodePort: {{ .Values.grafana.service.nodePort }}
  selector:
    app: {{ .Values.grafana.service.name }}
