apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nginxReverseProxy.configMapName }}
data:
  nginx.conf: |
    events {}

    http {
        server {
            listen {{ .Values.nginxReverseProxy.service.targetPort }};

            location / {
                proxy_pass http://{{ .Values.grafana.service.name }}:{{ .Values.grafana.service.port }};
                proxy_set_header X-WEBAUTH-USER autologin_user;
            }
        }
    }

