apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-nats-adapter
  labels:
    app: prometheus-nats-adapter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-nats-adapter
  template:
    metadata:
      name: prometheus-nats-adapter
      labels:
        app: prometheus-nats-adapter
    spec:
      containers:
        - name: prometheus-nats-adapter
          image: {{ .Values.prometheusNatsAdapter.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: NATS_URL
              value: {{ .Values.prometheusNatsAdapter.natsUrl }}
            - name: NATS_STREAM
              value: {{ .Values.prometheusNatsAdapter.natsStream }}
            - name: NATS_SUBJECT
              value: {{ .Values.prometheusNatsAdapter.natsSubject }}
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus-nats-adapter
spec:
  selector:
    app: prometheus-nats-adapter
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
