apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-app-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quarkus-app-3
  template:
    metadata:
      labels:
        app: quarkus-app-3
    spec:
      containers:
        - name: quarkus-app-3
          image: anejvovcakjob/aces:microservice-demo
          ports:
            - containerPort: {{ .Values.quarkusApp3.containerPort }}
          env:
            - name: CUSTOMERS_API_URL
              value: {{ .Values.quarkusApp3.customersApiUrl }}
---
apiVersion: v1
kind: Service
metadata:
  name: quarkus-app-3
spec:
  selector:
    app: quarkus-app-3
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.quarkusApp3.port }}
      targetPort: {{ .Values.quarkusApp3.targetPort }}
