apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.service.name }}
spec:
  selector:
    app: prometheus-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: ClusterIP