name: Docker Compose Test

on:
  push:
    branches:
      - main
      - refact-jetstream
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Check for active ports
      - name: Check for active ports
        run: |
          echo "Listing active ports..."
          sudo netstat -tuln

      # Step 3: Set up Docker Compose
      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v1

      # Step 4: Start Docker Compose
      - name: Start Docker Compose services
        run: docker-compose up -d

      # Step 5: Wait for services to be healthy
      - name: Wait for services to be healthy
        run: |
          echo "Waiting for services to be healthy..."
          sleep 60

      # Step 6: Check if all services are running
      - name: Check Docker Compose service status
        run: |
          echo "Checking services' status..."
          docker-compose ps

          # Count number of running containers
          RUNNING_CONTAINERS=$(docker-compose ps | grep 'Up' | wc -l)

          # Check if all containers are running (remove header line)
          TOTAL_CONTAINERS=$(docker-compose ps | wc -l | xargs -I {} expr {} - 1)

          if [ "$RUNNING_CONTAINERS" -ne "$TOTAL_CONTAINERS" ]; then
            echo "Not all containers are up and running. Failing the test."
            exit 1
          else
            echo "All containers are up and running."
          fi

      # Step 7: Tear down services after the test
      - name: Tear down Docker Compose
        if: always()
        run: docker-compose down
